spring:
  data:
    mongodb:
      username: barneymorris
      password: barneymorris
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090