spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: barneymorris
    password: barneymorris
    driver-class-name: org.postgresql.Driver
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.barneymorris.ecommerce.kafka.OrderConfirmation,paymentConfirmation:com.barneymorris.ecommerce.kafka.PaymentNotificationRequest
  mail:
    host: localhost
    port: 1025
    username: barneymorris
    password: barneymorris
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port:
    8040